// Handles every client always scans for award records, so the network
// leaderboard stays in sync across machines — even for tangled-hosted (tngl.sh)
// accounts the Bluesky relay/firehose can't see. Add each demo participant's
// handle here so all three stations tally each other's Gold Knots every cycle.
export const LEADERBOARD_SEED_HANDLES = [
  'karakoz.tngl.sh',
  'borbor84.tngl.sh',
  'basa24.bsky.social',
];

// Seed repos to scan on tangled.org (handles resolved to DIDs at runtime)
export const SEED_REPOS = [
  { handle: 'karakoz.tngl.sh', repo: 'sunsteadboilerplate' },
  { handle: 'tangled.org', repo: 'core' },
  { handle: 'tangled.org', repo: 'docs' },
  { handle: 'val.bsky.social', repo: 'atproto' },
];

// Fallback mock bounties — shown when live XRPC fetch is unavailable.
// These mirror the structure of real parsed sh.tangled.repo.issue records.
export const MOCK_BOUNTIES = [
  {
    id: 'bounty-001',
    issueTitle: 'Fix memory leak in WebSocket connection handler',
    issueBody: `After 1000+ concurrent connections, RSS grows unbounded. Profiling shows the connection map is never cleaned up on disconnect events. This is causing OOM crashes in production deployments.\n\n**Steps to reproduce:**\n\`\`\`\ncargo run --example stress_test -- --connections 1200\n\`\`\`\n\nExpected: stable memory. Actual: 2GB+ after 30 minutes.\n\n#bounty`,
    issueUri: 'at://did:plc:mock001/sh.tangled.repo.issue/tid001',
    issueUrl: 'https://tangled.org/systems_dev/netcore/issues/42',
    repo: { name: 'netcore', handle: 'systems_dev.tngl.sh', ownerDid: 'did:plc:mock001', stars: 284, language: 'rust', authorityWeight: 0.87 },
    keywords: ['rust', 'websocket', 'async', 'memory-leak', 'networking', 'tokio', 'concurrency', 'performance', 'server', 'tcp'],
    topKeywords: ['rust', 'websocket', 'memory-leak'],
    difficulty: 4,
    summary: 'Fix unbounded memory growth in WebSocket connection handler under high concurrency.',
    status: 'open',
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    fetchedAt: new Date().toISOString(),
  },
  {
    id: 'bounty-002',
    issueTitle: 'Add keyboard shortcuts to the inline code editor',
    issueBody: `The embedded code editor in issue bodies lacks standard shortcuts. Users expect:\n- Ctrl+/ to toggle line comments\n- Ctrl+D to duplicate current line\n- Tab/Shift+Tab for indent\n\nCurrently all three are no-ops. This is a friction point for power users.\n\n#bounty`,
    issueUri: 'at://did:plc:mock002/sh.tangled.repo.issue/tid002',
    issueUrl: 'https://tangled.org/uicraft/editr/issues/17',
    repo: { name: 'editr', handle: 'uicraft.tngl.sh', ownerDid: 'did:plc:mock002', stars: 61, language: 'typescript', authorityWeight: 0.54 },
    keywords: ['typescript', 'editor', 'keyboard', 'ui', 'ux', 'codemirror', 'keybindings', 'frontend', 'accessibility', 'shortcut'],
    topKeywords: ['typescript', 'editor', 'keybindings'],
    difficulty: 2,
    summary: 'Implement standard keyboard shortcuts (comment, duplicate, indent) in the embedded code editor.',
    status: 'open',
    createdAt: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    fetchedAt: new Date().toISOString(),
  },
  {
    id: 'bounty-003',
    issueTitle: 'Optimize slow N+1 query in repository list endpoint',
    issueBody: `GET /repos takes 800ms average for users with 50+ repos. EXPLAIN shows it fires a separate query per repo to fetch the last commit. Should be a single join.\n\nTrace:\n\`\`\`\nSELECT * FROM repos WHERE owner_did = $1  -- 1 query\nSELECT * FROM commits WHERE repo_id = $2  -- N queries (one per repo)\n\`\`\`\n\n#bounty`,
    issueUri: 'at://did:plc:mock003/sh.tangled.repo.issue/tid003',
    issueUrl: 'https://tangled.org/dataeng/repostore/issues/91',
    repo: { name: 'repostore', handle: 'dataeng.tngl.sh', ownerDid: 'did:plc:mock003', stars: 412, language: 'go', authorityWeight: 0.91 },
    keywords: ['go', 'database', 'sql', 'postgresql', 'query', 'performance', 'n+1', 'orm', 'optimization', 'backend'],
    topKeywords: ['go', 'database', 'optimization'],
    difficulty: 3,
    summary: 'Eliminate N+1 query in the repository list endpoint by replacing sequential queries with a single JOIN.',
    status: 'open',
    createdAt: new Date(Date.now() - 14 * 60 * 60 * 1000).toISOString(),
    fetchedAt: new Date().toISOString(),
  },
  {
    id: 'bounty-004',
    issueTitle: 'Implement BLAKE3 file integrity verification for knot uploads',
    issueBody: `We currently use SHA-256 for verifying uploaded pack files. BLAKE3 is ~3x faster and supports streaming verification. Switching would meaningfully reduce push latency for large repos.\n\nWould require:\n1. Adding the blake3 crate\n2. Updating the pack file header format\n3. Migration path for existing objects\n\nThis is a non-trivial protocol change. #bounty`,
    issueUri: 'at://did:plc:mock004/sh.tangled.repo.issue/tid004',
    issueUrl: 'https://tangled.org/tangled.org/core/issues/203',
    repo: { name: 'core', handle: 'tangled.org', ownerDid: 'did:plc:mock004', stars: 1840, language: 'go', authorityWeight: 0.99 },
    keywords: ['go', 'cryptography', 'blake3', 'hashing', 'protocol', 'git', 'performance', 'streaming', 'integrity', 'migration'],
    topKeywords: ['cryptography', 'blake3', 'protocol'],
    difficulty: 5,
    summary: 'Replace SHA-256 with BLAKE3 for pack file integrity verification in knot upload protocol.',
    status: 'open',
    createdAt: new Date(Date.now() - 26 * 60 * 60 * 1000).toISOString(),
    fetchedAt: new Date().toISOString(),
  },
  {
    id: 'bounty-005',
    issueTitle: 'Fix race condition in concurrent job queue processor',
    issueBody: `When multiple worker goroutines process jobs simultaneously, we occasionally see duplicate processing. The claim-and-lock step is not atomic. Under load (~500 jobs/sec) we get ~0.3% duplicate executions.\n\n\`\`\`go\n// bug: SELECT then UPDATE are not atomic\njob := db.QueryRow("SELECT * FROM jobs WHERE status='pending' LIMIT 1")\ndb.Exec("UPDATE jobs SET status='running' WHERE id=$1", job.ID)\n\`\`\`\n\n#bounty`,
    issueUri: 'at://did:plc:mock005/sh.tangled.repo.issue/tid005',
    issueUrl: 'https://tangled.org/infra_dev/jobqueue/issues/34',
    repo: { name: 'jobqueue', handle: 'infra_dev.tngl.sh', ownerDid: 'did:plc:mock005', stars: 193, language: 'go', authorityWeight: 0.79 },
    keywords: ['go', 'concurrency', 'race-condition', 'database', 'postgresql', 'locking', 'atomicity', 'worker', 'queue', 'backend'],
    topKeywords: ['go', 'race-condition', 'concurrency'],
    difficulty: 4,
    summary: 'Fix non-atomic job claim step that causes duplicate processing under concurrent load.',
    status: 'open',
    createdAt: new Date(Date.now() - 31 * 60 * 60 * 1000).toISOString(),
    fetchedAt: new Date().toISOString(),
  },
  {
    id: 'bounty-006',
    issueTitle: 'Add dark/light mode toggle with system preference detection',
    issueBody: `The app is dark-only right now. We need:\n1. A toggle button in the nav\n2. Respect prefers-color-scheme on first load\n3. Persist user choice in localStorage\n4. Smooth transition (no flash on load)\n\nCSS custom properties are already set up on :root. Just needs the JS wiring. #bounty`,
    issueUri: 'at://did:plc:mock006/sh.tangled.repo.issue/tid006',
    issueUrl: 'https://tangled.org/uicraft/editr/issues/22',
    repo: { name: 'webapp', handle: 'frontend_labs.tngl.sh', ownerDid: 'did:plc:mock006', stars: 88, language: 'typescript', authorityWeight: 0.60 },
    keywords: ['typescript', 'css', 'dark-mode', 'ui', 'accessibility', 'localStorage', 'frontend', 'theme', 'javascript', 'ux'],
    topKeywords: ['typescript', 'dark-mode', 'ui'],
    difficulty: 2,
    summary: 'Add dark/light theme toggle that detects system preference and persists user choice.',
    status: 'open',
    createdAt: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
    fetchedAt: new Date().toISOString(),
  },
  {
    id: 'bounty-007',
    issueTitle: 'Zero-copy deserialization for AT Protocol CBOR messages',
    issueBody: `Our firehose subscriber deserializes every CBOR message into a fully owned struct. Under high throughput (50k events/sec) this generates enormous GC pressure in Go.\n\nWe should implement zero-copy deserialization using unsafe pointer tricks or a custom arena allocator. This requires deep knowledge of CBOR encoding and Go's memory model. #bounty`,
    issueUri: 'at://did:plc:mock007/sh.tangled.repo.issue/tid007',
    issueUrl: 'https://tangled.org/tangled.org/core/issues/287',
    repo: { name: 'core', handle: 'tangled.org', ownerDid: 'did:plc:mock004', stars: 1840, language: 'go', authorityWeight: 0.99 },
    keywords: ['go', 'performance', 'cbor', 'protocol', 'memory', 'concurrency', 'serialization', 'atproto', 'unsafe', 'gc'],
    topKeywords: ['go', 'cbor', 'performance'],
    difficulty: 5,
    summary: 'Implement zero-copy CBOR deserialization for the AT Protocol firehose to eliminate GC pressure.',
    status: 'open',
    createdAt: new Date(Date.now() - 48 * 60 * 60 * 1000).toISOString(),
    fetchedAt: new Date().toISOString(),
  },
  {
    id: 'bounty-008',
    issueTitle: 'Fix broken internal links in API documentation',
    issueBody: `Several anchor links in docs/api.md point to headings that were renamed in the last refactor. Affected links:\n- "Authentication" → "#auth-flow"\n- "Rate Limits" → "#limits"\n- "Error Codes" → "#errors"\n\nJust a docs fix, no code changes needed. #bounty`,
    issueUri: 'at://did:plc:mock008/sh.tangled.repo.issue/tid008',
    issueUrl: 'https://tangled.org/tangled.org/docs/issues/14',
    repo: { name: 'docs', handle: 'tangled.org', ownerDid: 'did:plc:mock004', stars: 1840, language: 'markdown', authorityWeight: 0.99 },
    keywords: ['docs', 'markdown', 'documentation', 'links', 'readme', 'api', 'reference', 'typo', 'formatting'],
    topKeywords: ['docs', 'markdown', 'documentation'],
    difficulty: 1,
    summary: 'Fix broken anchor links in the API documentation after heading renames.',
    status: 'open',
    createdAt: new Date(Date.now() - 7 * 60 * 60 * 1000).toISOString(),
    fetchedAt: new Date().toISOString(),
  },
  {
    id: 'bounty-009',
    issueTitle: 'Implement JWT refresh token rotation with sliding expiry',
    issueBody: `Current auth: access token (15min TTL), refresh token (7d, no rotation). If a refresh token is stolen, an attacker has a 7-day window.\n\nWe need sliding window refresh token rotation:\n- Issue a new refresh token on each use\n- Invalidate the old one\n- Detect reuse attacks (if old token is reused, invalidate the whole family)\n\n#bounty`,
    issueUri: 'at://did:plc:mock009/sh.tangled.repo.issue/tid009',
    issueUrl: 'https://tangled.org/auth_pro/sessionkit/issues/78',
    repo: { name: 'sessionkit', handle: 'auth_pro.tngl.sh', ownerDid: 'did:plc:mock009', stars: 347, language: 'go', authorityWeight: 0.89 },
    keywords: ['go', 'authentication', 'jwt', 'security', 'oauth', 'token', 'refresh', 'rotation', 'backend', 'cryptography'],
    topKeywords: ['security', 'jwt', 'authentication'],
    difficulty: 4,
    summary: 'Implement sliding-window refresh token rotation with reuse-attack detection for the auth service.',
    status: 'open',
    createdAt: new Date(Date.now() - 20 * 60 * 60 * 1000).toISOString(),
    fetchedAt: new Date().toISOString(),
  },
  {
    id: 'bounty-010',
    issueTitle: 'Add gRPC health check endpoint for Kubernetes liveness probes',
    issueBody: `Our gRPC service doesn't implement the standard health.proto spec, so Kubernetes can't determine pod health. We need to add the grpc.health.v1.Health service.\n\nThis is a straightforward addition — just implement the Check and Watch RPCs. Should be < 50 lines. #bounty`,
    issueUri: 'at://did:plc:mock010/sh.tangled.repo.issue/tid010',
    issueUrl: 'https://tangled.org/infra_dev/grpckit/issues/12',
    repo: { name: 'grpckit', handle: 'infra_dev.tngl.sh', ownerDid: 'did:plc:mock005', stars: 193, language: 'go', authorityWeight: 0.79 },
    keywords: ['go', 'grpc', 'kubernetes', 'devops', 'infrastructure', 'health-check', 'proto', 'liveness', 'deployment', 'api'],
    topKeywords: ['go', 'grpc', 'kubernetes'],
    difficulty: 3,
    summary: 'Add grpc.health.v1.Health service implementation for Kubernetes liveness/readiness probes.',
    status: 'open',
    createdAt: new Date(Date.now() - 36 * 60 * 60 * 1000).toISOString(),
    fetchedAt: new Date().toISOString(),
  },
  {
    id: 'bounty-011',
    issueTitle: 'Port Python data pipeline to async with asyncio',
    issueBody: `Our ETL pipeline processes ~10M records/day using synchronous Python. It saturates a single core and takes 4 hours. Switching to asyncio + aiohttp for the fetch phase should get it under 1 hour.\n\nThe transform and load phases are CPU-bound (use ProcessPoolExecutor). The bottleneck is the fetch phase (I/O bound). #bounty`,
    issueUri: 'at://did:plc:mock011/sh.tangled.repo.issue/tid011',
    issueUrl: 'https://tangled.org/data_sci/pipeflow/issues/55',
    repo: { name: 'pipeflow', handle: 'data_sci.tngl.sh', ownerDid: 'did:plc:mock011', stars: 129, language: 'python', authorityWeight: 0.68 },
    keywords: ['python', 'asyncio', 'async', 'aiohttp', 'performance', 'etl', 'data-pipeline', 'concurrency', 'backend', 'optimization'],
    topKeywords: ['python', 'asyncio', 'performance'],
    difficulty: 3,
    summary: 'Refactor the synchronous ETL fetch phase to asyncio to reduce pipeline runtime from 4h to under 1h.',
    status: 'open',
    createdAt: new Date(Date.now() - 55 * 60 * 60 * 1000).toISOString(),
    fetchedAt: new Date().toISOString(),
  },
  {
    id: 'bounty-012',
    issueTitle: 'Implement WebAssembly plugin sandbox for user-provided scripts',
    issueBody: `We want to allow users to write custom data transform plugins. The plugin API needs to run untrusted code safely. WASM is the right isolation layer.\n\nNeeds:\n1. A WASM runtime (wasmtime or wasmer) embedded in the Go service\n2. A defined ABI for the plugin interface (pass/return JSON blobs)\n3. CPU and memory limits per invocation\n4. Timeout enforcement\n\n#bounty`,
    issueUri: 'at://did:plc:mock012/sh.tangled.repo.issue/tid012',
    issueUrl: 'https://tangled.org/dataeng/repostore/issues/99',
    repo: { name: 'pluginhost', handle: 'systems_dev.tngl.sh', ownerDid: 'did:plc:mock001', stars: 284, language: 'go', authorityWeight: 0.87 },
    keywords: ['go', 'webassembly', 'wasm', 'security', 'sandbox', 'plugin', 'runtime', 'wasmtime', 'isolation', 'architecture'],
    topKeywords: ['wasm', 'security', 'sandbox'],
    difficulty: 5,
    summary: 'Embed a WASM runtime with CPU/memory sandboxing to safely execute user-provided plugin scripts.',
    status: 'open',
    createdAt: new Date(Date.now() - 72 * 60 * 60 * 1000).toISOString(),
    fetchedAt: new Date().toISOString(),
  },
  {
    id: 'bounty-013',
    issueTitle: 'Add pagination to the repository file browser',
    issueBody: `Repos with 500+ files in a directory time out loading the file tree. We need server-side pagination for directory listings. The API already supports a cursor parameter — just need to wire up the frontend to load more on scroll or button click. #bounty`,
    issueUri: 'at://did:plc:mock013/sh.tangled.repo.issue/tid013',
    issueUrl: 'https://tangled.org/uicraft/filebrowse/issues/8',
    repo: { name: 'filebrowse', handle: 'uicraft.tngl.sh', ownerDid: 'did:plc:mock002', stars: 61, language: 'typescript', authorityWeight: 0.54 },
    keywords: ['typescript', 'react', 'pagination', 'ui', 'frontend', 'infinite-scroll', 'api', 'cursor', 'ux', 'performance'],
    topKeywords: ['typescript', 'react', 'pagination'],
    difficulty: 2,
    summary: 'Add cursor-based pagination to directory listings in the file browser for large repos.',
    status: 'open',
    createdAt: new Date(Date.now() - 10 * 60 * 60 * 1000).toISOString(),
    fetchedAt: new Date().toISOString(),
  },
  {
    id: 'bounty-014',
    issueTitle: 'Implement distributed tracing with OpenTelemetry',
    issueBody: `We have 6 microservices with no shared tracing. Debugging latency issues requires manually correlating logs across services. Need to add OTel instrumentation:\n\n1. Auto-instrument HTTP and gRPC handlers\n2. Propagate trace context via W3C Trace Context headers\n3. Export to OTLP endpoint (configurable)\n\n#bounty`,
    issueUri: 'at://did:plc:mock014/sh.tangled.repo.issue/tid014',
    issueUrl: 'https://tangled.org/infra_dev/tracekit/issues/3',
    repo: { name: 'tracekit', handle: 'infra_dev.tngl.sh', ownerDid: 'did:plc:mock005', stars: 193, language: 'go', authorityWeight: 0.79 },
    keywords: ['go', 'opentelemetry', 'observability', 'tracing', 'devops', 'grpc', 'microservices', 'monitoring', 'infrastructure', 'backend'],
    topKeywords: ['go', 'opentelemetry', 'observability'],
    difficulty: 4,
    summary: 'Add OpenTelemetry distributed tracing across HTTP and gRPC handlers with W3C context propagation.',
    status: 'open',
    createdAt: new Date(Date.now() - 42 * 60 * 60 * 1000).toISOString(),
    fetchedAt: new Date().toISOString(),
  },
  {
    id: 'bounty-015',
    issueTitle: 'Add rate limiting middleware with Redis token bucket',
    issueBody: `The API has no rate limiting. A single aggressive client can DoS the service. We need a token bucket rate limiter backed by Redis for distributed deployments.\n\nRequirements:\n- Per-DID limits (100 req/min default, configurable)\n- Per-IP fallback for unauthenticated requests\n- Return 429 with Retry-After header\n- Redis Lua script for atomic bucket operations\n\n#bounty`,
    issueUri: 'at://did:plc:mock015/sh.tangled.repo.issue/tid015',
    issueUrl: 'https://tangled.org/auth_pro/sessionkit/issues/82',
    repo: { name: 'apigateway', handle: 'auth_pro.tngl.sh', ownerDid: 'did:plc:mock009', stars: 347, language: 'go', authorityWeight: 0.89 },
    keywords: ['go', 'redis', 'rate-limiting', 'middleware', 'api', 'security', 'token-bucket', 'performance', 'backend', 'lua'],
    topKeywords: ['go', 'rate-limiting', 'redis'],
    difficulty: 3,
    summary: 'Implement Redis-backed token bucket rate limiting middleware with per-DID and per-IP limits.',
    status: 'open',
    createdAt: new Date(Date.now() - 18 * 60 * 60 * 1000).toISOString(),
    fetchedAt: new Date().toISOString(),
  },
];

// Difficulty labels
export const DIFFICULTY_LABELS = {
  1: 'Trivial',
  2: 'Easy',
  3: 'Medium',
  4: 'Hard',
  5: 'Expert',
};

export const DIFFICULTY_DESCRIPTIONS = {
  1: 'Typos, broken links, docs and comment fixes.',
  2: 'Small UI changes, config tweaks, simple additions.',
  3: 'New features, refactors, tests, endpoint additions.',
  4: 'Performance, security, concurrency, architecture.',
  5: 'Cryptography, protocols, compilers, kernel-level work.',
};

// Demo users — the "current user" is identified by the handle stored in localStorage.
// These are used for the profile page and for ranking when the handle matches.
export const DEMO_USERS = {
  'demo.tngl.sh': {
    did: 'did:plc:demouser',
    handle: 'demo.tngl.sh',
    displayName: 'Demo Hunter',
    avatar: null,
    pdsEndpoint: 'https://tangled.org',
    following: ['did:plc:mock001', 'did:plc:mock003', 'did:plc:mock004', 'did:plc:mock009'],
    starredRepos: ['at://did:plc:mock001/sh.tangled.repo/netcore', 'at://did:plc:mock004/sh.tangled.repo/core'],
    bountyProfile: {
      totalCompleted: 0,
      skillBreakdown: { typescript: 4, react: 2, css: 1 },
      avgDifficulty: 2.5,
      completionStreak: 0,
      totalPoints: 0,
      public: true,
      lastUpdated: new Date().toISOString(),
    },
    awards: [],
  },
};
